
server:
  port: 8081
mybatis:
  config-locations: classpath:mapping/confg.xml
  mapper-locations: classpath:mapping/mapper/*.xml
  type-aliases-package: com.jk.model
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liu?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    solr:
      host: http://127.0.0.1:8080/solr
    thymeleaf:
      cache: false
      mode: LEGACYHTML5

